### ISSUE TITLE
Enable full tests across Java, Python, Ghidra versions

### ISSUE THREAD

**Issue by clearbluejar** [clearbluejar/ghidriff#48]
Currently, the devcontainer can only test one version. Use github actions to test across versions.

**Comment by clearbluejar** [comment]
Currently failing with: https://github.com/clearbluejar/ghidriff/actions/runs/6588742165/job/17901707946

```
/usr/bin/docker exec  015ac5f6b179b05b7be40f56fd62fded0310ba92620f19cdf9477d26d49f5517 sh -c "cat /etc/*release | grep ^ID"
node:internal/fs/utils:347
    throw err;
    ^

Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_fa9a8766-3f44-49b3-befb-0e396a8d6fd1'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at Object.appendFileSync (node:fs:2264:6)
    at Object.issueFileCommand (/__w/_actions/actions/checkout/v3/dist/index.js:2950:8)
    at Object.saveState (/__w/_actions/actions/checkout/v3/dist/index.js:2867:31)
    at Object.8647 (/__w/_actions/actions/checkout/v3/dist/index.js:2326:10)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:[18](https://github.com/clearbluejar/ghidriff/actions/runs/6588742165/job/17901707946#step:3:19)256:43)
    at Object.2565 (/__w/_actions/actions/checkout/v3/dist/index.js:146:34)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:18256:43)
    at Object.9[21](https://github.com/clearbluejar/ghidriff/actions/runs/6588742165/job/17901707946#step:3:22)0 (/__w/_actions/actions/checkout/v3/dist/index.js:1141:36) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/__w/_temp/_runner_file_commands/save_state_fa9a8766-3f44-49b3-befb-0e396a8d6fd1'
}
```

This is because github actions do not allow a non-root user.. without a workaround. https://github.com/actions/checkout/issues/1014#issuecomment-1718187132
