### ISSUE TITLE
Container/nested files not working

### ISSUE THREAD

**Issue by JxxIT** [clearbluejar/ghidriff#98]
I tried to diff two files, but I get the following exception:

<details><summary>Exception</summary>
<p>

```
INFO | ghidriff | Init Ghidra Diff Engine...
INFO | ghidriff | Engine Console Log: INFO
INFO | ghidriff | Engine File Log:  ghidriffs/ghidriff.log INFO
INFO | ghidriff | Starting Ghidra...
INFO  Using log config file: jar:file:/opt/homebrew/Caskroom/ghidra/11.1.2-20240709/ghidra_11.1.2_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: /Users/jxxit/ghidriffs/ghidriff.log (LoggingInitialization)
INFO  Loading user preferences: /Users/jxxit/Library/ghidra/ghidra_11.1.2_PUBLIC/preferences (Preferences)
INFO  Loading previous preferences: /Users/jxxit/.ghidra/.ghidra_11.0.1_PUBLIC/preferences (Preferences)
INFO  Searching for classes... (ClassSearcher)
INFO  Ignoring class 'ghidra.GhidraClassLoader' from '/opt/homebrew/Caskroom/ghidra/11.1.2-20240709/ghidra_11.1.2_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar'. Already found at '/opt/homebrew/Caskroom/ghidra/11.1.2-20240709/ghidra_11.1.2_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar'. (ClassSearcher)
INFO  Ignoring class 'generic.jar.GClassLoader' from '/opt/homebrew/Caskroom/ghidra/11.1.2-20240709/ghidra_11.1.2_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar'. Already found at '/opt/homebrew/Caskroom/ghidra/11.1.2-20240709/ghidra_11.1.2_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar'. (ClassSearcher)
INFO  Class search complete (900 ms) (ClassSearcher)
INFO  Initializing SSL Context (SSLContextInitializer)
INFO  Initializing Random Number Generator... (SecureRandomFactory)
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)
INFO | ghidriff | GHIDRA_INSTALL_DIR: /opt/homebrew/Caskroom/ghidra/11.1.2-20240709/ghidra_11.1.2_PUBLIC
INFO | ghidriff | GHIDRA 11.1.2  Build Date: 2024-Jul-09 1157 EDT Release: PUBLIC
INFO | ghidriff | Engine Args:
INFO | ghidriff | 	old:                ['/Applications/App1.app/Contents/MacOS/App']
INFO | ghidriff | 	new:                [['/Applications/App2.app/Contents/MacOS/App']]
INFO | ghidriff | 	engine:             VersionTrackingDiff
INFO | ghidriff | 	output_path:        ghidriffs
INFO | ghidriff | 	summary:            False
INFO | ghidriff | 	project_location:   ghidra_projects
INFO | ghidriff | 	project_name:       ghidriff
INFO | ghidriff | 	symbols_path:       symbols
INFO | ghidriff | 	threaded:           True
INFO | ghidriff | 	force_analysis:     False
INFO | ghidriff | 	force_diff:         False
INFO | ghidriff | 	no_symbols:         False
INFO | ghidriff | 	log_level:          INFO
INFO | ghidriff | 	file_log_level:     INFO
INFO | ghidriff | 	log_path:           ghidriff.log
INFO | ghidriff | 	va:                 False
INFO | ghidriff | 	min_func_len:       10
INFO | ghidriff | 	use_calling_counts: False
INFO | ghidriff | 	gdt:                []
INFO | ghidriff | 	bsim:               True
INFO | ghidriff | 	bsim_full:          False
INFO | ghidriff | 	max_ram_percent:    60.0
INFO | ghidriff | 	print_flags:        False
INFO | ghidriff | 	jvm_args:           None
INFO | ghidriff | 	side_by_side:       False
INFO | ghidriff | 	max_section_funcs:  200
INFO | ghidriff | 	md_title:           None
INFO | ghidriff | Setting Up Ghidra Project...
INFO  Creating project: /Users/jxxit/ghidriffs/ghidra_projects/ghidriff-App-App/ghidriff-App-App (DefaultProject)
INFO | ghidriff | Created project: ghidriff-App-App
INFO | ghidriff | Project Location: /Users/jxxit/ghidriffs/ghidra_projects/ghidriff-App-App/
INFO | ghidriff | Importing /Applications/App1.app/Contents/MacOS/App as App-ac3865
INFO  Starting cache cleanup: /var/tmp/jxxit-ghidra/fscache2 (FileCacheMaintenanceDaemon)
INFO  Finished cache cleanup, estimated storage used: 0 (FileCacheMaintenanceDaemon)
INFO  No load spec found for import file: /Applications/App1.app/Contents/MacOS/App (AutoImporter)
Traceback (most recent call last):
  File "GhidraProject.java", line 653, in ghidra.base.project.GhidraProject.importProgram
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/ghidriff", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ghidriff/__main__.py", line 73, in main
    d.setup_project(binary_paths, project_path, project_name, symbols_path)
  File "/opt/homebrew/lib/python3.11/site-packages/ghidriff/ghidra_diff_engine.py", line 470, in setup_project
    program = project.importProgram(program_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ghidra.app.util.opinion.ghidra.app.util.opinion.LoadException: ghidra.app.util.opinion.LoadException: No load spec found
```

</p>
</details>

**Comment by clearbluejar** [comment]
`ghidra.app.util.opinion.ghidra.app.util.opinion.LoadException: ghidra.app.util.opinion.LoadException: No load spec found`

This error from your log means the file you are attempting is not understood by Ghidra.  There is no loader that matches the file you are attempting to diff. Ghidra has loaders for the following types of files:

![image](https://github.com/user-attachments/assets/2bdf7d75-0436-4104-a165-f53d88ef723a)

Also listed here: https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion

**Comment by JxxIT** [comment]
@clearbluejar I can import it manually in ghidra, but it has nested files. It is a Mach-O file, that contains two binaries.

**Comment by clearbluejar** [comment]
Ah, try extracting the files and diffing. Is it a universal mach-o with both architectures?  just select the correct arch from both.

**Comment by JxxIT** [comment]
Great, that worked!

For anyone with the same issue, I solved it this way:
1. Open Ghidra
2. Import your Container File, and select that it has multiple files.
3. Right click on the imported file, and choose export. Select Original File
4. Repeat for the other file, and run ghidriff.
